name: Update Stories

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger story fetch
        run: |
          curl -X GET "https://www.theglobalrecord.com/api/save-stories" -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" --fail --silent --show-error
